name: Random KSM Test
on:
  workflow_dispatch:

jobs:
  ksm-test-random:
    runs-on: ubuntu-latest

    steps:

      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.DEMO_SECRET }}
          secrets: |
          _tVhrPo8vsQLbL2euYfVYg/password > pwd
      
      - name: View password
        run: |
          echo 'pwd: ${{ steps.ksecrets.outputs.pwd }}'
