on: 
  push:
    branches: [ master ]

jobs:
  buildexecutable:
    runs-on: ubuntu-latest
    name: Build with Keeper secrets
    steps:

      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
              # Reference records by UID
              _tVhrPo8vsQLbL2euYfVYg/field/password > env.PASSWORD


      # View secret stored into 'PASSWORD' environment variable
      - name: Print password
        run: |
          echo "Password is ${{ env.PASSWORD }}"
